#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime environment changes to make the snap work here.  You may also insert security confinement/deprecation/obsoletion notice of the snap here.

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

# GTK theme integration (we have Qt fetch the GTK theme mirroring the host Qt theme...)
#export QT_QPA_PLATFORMTHEME=kde

# Check if the last parameter is a file, and if so, add the argument "--no-checks-for-updates" BEFORE it.
last="${@:$#}" # last parameter 
length=$(($#-1))
args=("${@:1:$length}")  # all parameters except the last

if [ -f "$last" ]; then
	${args} --no-check-for-updates "$last"
else
	${@} --no-check-for-updates
fi
